name: q2book
channels:
  - qiime2/label/r2020.11
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-rhtslib=1.22.0
  - python_abi=3.6
  - idna=2.10
  - r-rcpp=1.0.5
  - _openmp_mutex=4.5
  - perl-constant=1.33
  - gsl=2.6
  - hdf5=1.10.5
  - perl-encode=2.88
  - harfbuzz=2.7.2
  - bioconductor-genomicranges=1.42.0
  - cffi=1.14.4
  - r-ps=1.5.0
  - jupyter_client=6.1.7
  - bioconductor-biocgenerics=0.36.0
  - tzlocal=2.1
  - q2-phylogeny=2020.11.1
  - xorg-libxtst=1.2.3
  - perl-extutils-makemaker=7.36
  - natsort=7.1.0
  - bioconductor-xvector=0.30.0
  - q2-metadata=2020.11.1
  - bowtie2=2.4.2
  - py=1.9.0
  - r-viridislite=0.3.0
  - r-pkgbuild=1.1.0
  - importlib-metadata=3.1.1
  - bioconductor-biobase=2.50.0
  - r-reshape2=1.4.4
  - click=7.1.2
  - q2-longitudinal=2020.11.1
  - liblapacke=3.8.0
  - perl-io-socket-ssl=2.066
  - msgpack-python=1.0.0
  - perl-mime-base64=3.15
  - nose=1.3.7
  - jedi=0.17.2
  - r-fansi=0.4.1
  - q2-sample-classifier=2020.11.1
  - r-pkgload=1.1.0
  - iniconfig=1.1.1
  - jupyter_core=4.7.0
  - matplotlib=3.2.2
  - q2-diversity=2020.11.1
  - ipywidgets=7.5.1
  - r-withr=2.3.0
  - perl-compress-raw-zlib=2.087
  - bleach=3.2.1
  - backcall=0.2.0
  - sysroot_linux-64=2.12
  - perl-json=4.02
  - samtools=1.11
  - matplotlib-base=3.2.2
  - pytz=2020.4
  - tbb=2020.2
  - certifi=2020.12.5
  - r-evaluate=0.14
  - sepp=4.3.10
  - ipython_genutils=0.2.0
  - lcms2=2.11
  - perl-net-ssleay=1.88
  - pillow=8.0.1
  - tornado=6.1
  - openjdk=11.0.8
  - bioconductor-rsamtools=2.6.0
  - bioconductor-dada2=1.18.0
  - r-rstudioapi=0.13
  - pluggy=0.13.1
  - bioconductor-biostrings=2.58.0
  - perl-common-sense=3.74
  - bioconductor-genomeinfodb=1.26.0
  - r-formatr=1.7
  - r-matrix=1.2_18
  - h5py=2.10.0
  - libiconv=1.16
  - perl-www-robotrules=6.02
  - r-hwriter=1.3.2
  - perl-xsloader=0.24
  - blast=2.10.1
  - tktable=2.10
  - libxcb=1.13
  - sed=4.8
  - pyopenssl=20.0.0
  - perl-xml-sax=1.02
  - hdmedians=0.14.1
  - r-jpeg=0.1_8.1
  - r-munsell=0.5.0
  - traitlets=4.3.3
  - libssh2=1.9.0
  - q2-gneiss=2020.11.1
  - r-ellipsis=0.3.1
  - yaml=0.2.5
  - _r-mutex=1.0.1
  - r-lattice=0.20_41
  - perl-file-listing=6.04
  - r-prettyunits=1.1.1
  - ncurses=6.2
  - pthread-stubs=0.4
  - fribidi=1.0.10
  - iqtree=2.0.3
  - perl-mozilla-ca=20180117
  - gfortran_linux-64=7.5.0
  - perl-scalar-list-utils=1.52
  - r-diffobj=0.3.2
  - cython=0.29.21
  - r-praise=1.0.0
  - perl-file-path=2.16
  - dendropy=4.5.1
  - perl-digest-md5=2.55
  - freetype=2.10.4
  - fastcluster=1.1.26
  - r-assertthat=0.2.1
  - q2-cutadapt=2020.11.1
  - pyzmq=20.0.0
  - libgcc=7.2.0
  - perl-xml-namespacesupport=1.12
  - kernel-headers_linux-64=2.6.32
  - q2templates=2020.11.1
  - wcwidth=0.2.5
  - scipy=1.5.3
  - libdeflate=1.6
  - libffi=3.3
  - seaborn-base=0.11.0
  - make=4.3
  - vsearch=2.7.0
  - perl-html-tagset=3.20
  - tk=8.6.10
  - libtiff=4.1.0
  - perl-base=2.23
  - more-itertools=8.6.0
  - r-ggplot2=3.3.2
  - xorg-libice=1.0.10
  - r-plyr=1.8.6
  - r-farver=2.0.3
  - ipython=7.16.1
  - alsa-lib=1.2.3
  - r-vegan=2.5_6
  - perl-types-serialiser=1.0
  - r-waldo=0.2.3
  - xorg-libx11=1.6.12
  - attrs=20.3.0
  - perl-data-dumper=2.173
  - icu=67.1
  - zstd=1.4.5
  - _libgcc_mutex=0.1
  - defusedxml=0.6.0
  - cutadapt=3.1
  - prompt-toolkit=3.0.8
  - q2-vsearch=2020.11.1
  - perl=5.26.2
  - bwidget=1.9.14
  - r-r6=2.5.0
  - urllib3=1.25.11
  - r-callr=3.5.1
  - perl-list-moreutils-xs=0.428
  - bioconductor-genomeinfodbdata=1.2.4
  - chardet=3.0.4
  - joblib=0.17.0
  - nbformat=5.0.8
  - pandoc=2.11.2
  - parso=0.7.1
  - r-stringi=1.5.3
  - bioconductor-summarizedexperiment=1.20.0
  - r-bh=1.72.0_3
  - r-rcppparallel=5.0.2
  - jupyterlab_pygments=0.1.2
  - r-gtable=0.3.0
  - ipykernel=5.3.4
  - r-lifecycle=0.2.0
  - q2cli=2020.11.1
  - r-digest=0.6.27
  - llvm-openmp=11.0.0
  - r-lambda.r=1.2.4
  - pandocfilters=1.4.2
  - xorg-libxdmcp=1.1.3
  - r-crayon=1.3.4
  - q2-quality-control=2020.11.1
  - q2-quality-filter=2020.11.1
  - zeromq=4.3.3
  - r-rcolorbrewer=1.1_2
  - perl-json-xs=2.34
  - htslib=1.11
  - webencodings=0.5.1
  - setuptools=49.6.0
  - importlib_metadata=3.1.1
  - perl-business-isbn=3.004
  - q2-feature-table=2020.11.1
  - r-latticeextra=0.6_29
  - perl-net-http=6.19
  - expat=2.2.9
  - ijson=3.1.3
  - bioconductor-matrixgenerics=1.2.0
  - r-cluster=2.1.0
  - zlib=1.2.11
  - psutil=5.7.3
  - gfortran_impl_linux-64=7.5.0
  - boost-cpp=1.70.0
  - r-brio=1.1.0
  - xorg-libxfixes=5.0.3
  - pandas=1.1.5
  - r-backports=1.2.1
  - r-colorspace=2.0_0
  - olefile=0.46
  - r-mass=7.3_53
  - threadpoolctl=2.1.0
  - q2-dada2=2020.11.1
  - pytest=6.1.2
  - r-testthat=3.0.0
  - cycler=0.10.0
  - terminado=0.9.1
  - perl-pathtools=3.75
  - kiwisolver=1.3.1
  - ca-certificates=2020.12.5
  - lz4-c=1.9.2
  - raxml=8.2.12
  - backports=1.0
  - mafft=7.475
  - perl-archive-tar=2.32
  - unifrac=0.20.1
  - r-magrittr=2.0.1
  - xorg-kbproto=1.0.7
  - perl-http-negotiate=6.01
  - r-vctrs=0.3.5
  - binutils_impl_linux-64=2.35.1
  - sina=1.7.1
  - bioconductor-delayedarray=0.16.0
  - widgetsnbextension=3.5.1
  - graphite2=1.3.13
  - curl=7.71.1
  - send2trash=1.5.0
  - r-zeallot=0.1.0
  - r-rematch2=2.1.2
  - xorg-libxrender=0.9.10
  - xorg-libxext=1.3.4
  - ld_impl_linux-64=2.35.1
  - q2-feature-classifier=2020.11.1
  - networkx=2.5
  - readline=8.0
  - bioconductor-shortread=1.48.0
  - xorg-inputproto=2.3.2
  - perl-lwp-protocol-https=6.07
  - r-pillar=1.4.7
  - libnghttp2=1.41.0
  - perl-lwp-mediatypes=6.04
  - q2-alignment=2020.11.1
  - dnaio=0.4.4
  - q2-diversity-lib=2020.11.1
  - async_generator=1.10
  - pcre=8.44
  - qiime2=2020.11.1
  - arb-bio-tools=6.0.6
  - future=0.18.2
  - lockfile=0.12.2
  - libsodium=1.0.18
  - r-futile.options=1.0.1
  - fasttree=2.1.10
  - perl-try-tiny=0.30
  - perl-list-moreutils=0.428
  - libpng=1.6.37
  - decorator=4.4.2
  - notebook=6.1.5
  - entrez-direct=13.9
  - lz4=3.1.1
  - krb5=1.17.2
  - brotlipy=0.7.0
  - wheel=0.36.1
  - libopenblas=0.3.10
  - bioconductor-s4vectors=0.28.0
  - zipp=3.4.0
  - typing_extensions=3.7.4.3
  - isa-l=2.30.0
  - jinja2=2.11.2
  - libcblas=3.8.0
  - r-nlme=3.1_150
  - q2-emperor=2020.11.1
  - gcc_impl_linux-64=7.5.0
  - r-permute=0.9_5
  - libstdcxx-ng=9.3.0
  - pexpect=4.8.0
  - r-rlang=0.4.9
  - perl-business-isbn-data=20140910.003
  - perl-http-cookies=6.04
  - hmmer=3.1b2
  - perl-exporter-tiny=1.002001
  - perl-carp=1.38
  - r-pkgconfig=2.0.3
  - biom-format=2.1.10
  - r-bitops=1.0_6
  - q2-demux=2020.11.1
  - r-scales=1.1.1
  - perl-uri=1.76
  - libgomp=9.3.0
  - numpy=1.19.4
  - xopen=1.0.1
  - binutils_linux-64=2.35
  - perl-io-html=1.001
  - toml=0.10.2
  - perl-xml-parser=2.44_01
  - perl-exporter=5.72
  - perl-test-requiresinternet=0.05
  - xorg-libxau=1.0.9
  - pyrsistent=0.17.3
  - pixman=0.40.0
  - q2-taxa=2020.11.1
  - liblapack=3.8.0
  - libwebp-base=1.1.0
  - perl-html-parser=3.72
  - sqlite=3.34.0
  - pyyaml=5.3.1
  - gxx_impl_linux-64=7.5.0
  - jpeg=9d
  - scikit-learn=0.23.1
  - xorg-recordproto=1.14.2
  - backports.functools_lru_cache=1.6.1
  - libev=4.33
  - xorg-libsm=1.2.3
  - perl-encode-locale=1.05
  - gxx_linux-64=7.5.0
  - perl-storable=3.15
  - blas=2.17
  - emperor=1.0.1
  - nbconvert=6.0.7
  - packaging=20.7
  - cachecontrol=0.12.6
  - bioconductor-biocparallel=1.24.0
  - scikit-bio=0.5.6
  - argon2-cffi=20.1.0
  - r-rprojroot=2.0.2
  - seaborn=0.11.0
  - nbclient=0.5.1
  - perl-xml-sax-expat=0.51
  - gettext=0.19.8.1
  - perl-compress-raw-bzip2=2.087
  - perl-http-message=6.18
  - perl-io-compress=2.087
  - perl-http-daemon=6.01
  - q2-deblur=2020.11.1
  - libedit=3.1.20191231
  - r-utf8=1.1.4
  - q2-composition=2020.11.1
  - r-matrixstats=0.57.0
  - r-base=4.0.2
  - libcurl=7.71.1
  - xorg-xextproto=7.3.0
  - cairo=1.16.0
  - libglib=2.66.3
  - r-cli=2.2.0
  - r-mgcv=1.8_33
  - bioconductor-genomicalignments=1.26.0
  - libgfortran-ng=7.5.0
  - r-isoband=0.2.3
  - libgfortran4=7.5.0
  - requests=2.25.0
  - r-desc=1.2.0
  - cryptography=3.3.1
  - r-processx=3.4.5
  - python=3.6.12
  - perl-xml-sax-base=1.09
  - xorg-renderproto=0.11.1
  - bibtexparser=1.1.0
  - r-rcurl=1.98_1.2
  - perl-html-tree=5.07
  - prometheus_client=0.9.0
  - six=1.15.0
  - bioconductor-iranges=2.24.0
  - xorg-libxi=1.7.10
  - q2-fragment-insertion=2020.11.1
  - pcre2=10.35
  - pygments=2.7.3
  - c-ares=1.17.1
  - pycparser=2.20
  - gneiss=0.4.6
  - r-snow=0.4_3
  - perl-file-temp=0.2304
  - libxml2=2.9.10
  - xorg-fixesproto=5.0
  - r-stringr=1.4.0
  - mistune=0.8.4
  - xz=5.2.5
  - openssl=1.1.1h
  - bzip2=1.0.8
  - fontconfig=2.13.1
  - testpath=0.4.4
  - perl-io-zlib=1.10
  - patsy=0.5.1
  - perl-socket=2.027
  - q2-types=2020.11.1
  - perl-libwww-perl=6.39
  - perl-ntlm=1.09
  - pyparsing=2.4.7
  - libarbdb=6.0.6
  - perl-app-cpanminus=1.7044
  - perl-http-date=6.02
  - glib=2.66.3
  - giflib=5.2.1
  - markupsafe=1.1.1
  - bioconductor-zlibbioc=1.36.0
  - libgcc-ng=9.3.0
  - perl-digest-hmac=1.03
  - r-futile.logger=1.4.3
  - deblur=1.1.0
  - pickleshare=0.7.5
  - r-tibble=3.0.4
  - libblas=3.8.0
  - sortmerna=2.0
  - statsmodels=0.12.1
  - entrypoints=0.3
  - nest-asyncio=1.4.3
  - pango=1.42.4
  - perl-parent=0.236
  - perl-xml-simple=2.25
  - xorg-xproto=7.0.31
  - r-glue=1.4.2
  - pysocks=1.7.1
  - python-dateutil=2.8.1
  - pigz=2.3.4
  - r-jsonlite=1.7.2
  - r-labeling=0.4.2
  - jsonschema=3.2.0
  - gcc_linux-64=7.5.0
  - pip=20.3.1
  - r-png=0.1_7
  - ptyprocess=0.6.0
  - bokeh=2.2.3
  - libuuid=2.32.1
  - perl-time-local=1.28
  - tabulate==0.8.8
  - pip:
    - jupyter-book
    - ghp-import
prefix: /home/jgc53/.conda/envs/q2book
